
name: Deploy to Staging
on:
  push:
    branches:
      - develop

jobs:
  publish:
    name: Publish to Staging
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v1
      - name: Deploy to Zeit Now
        run: now --token $ZEIT_TOKEN
        env:
          ZEIT_TOKEN: ${{ secrets.ZEIT_TOKEN }}
