
name: Deploy to Now
on:
  push:
    branches:
      - master

jobs:
  publish:
    name: Publish to prod
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v1
      - name: Deploy Frontend to Production
        run: now --token $ZEIT_TOKEN --prod
        env:
          ZEIT_TOKEN: ${{ secrets.ZEIT_TOKEN }}
