
name: Deploy to Now
on: [push]

jobs:
  filteroutmaster:
    name: Filter out master branch
    runs-on: ubuntu-latest
    needs: [deploy]
    steps:
      - name: Filter out master branch
        uses: actions/bin/filter@master
        with:
          args: "branch master"

  publish:
    name: Publish to prod
    runs-on: ubuntu-latest
    needs: [filteroutmaster]
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v1
      - name: Deploy on Zeit - Prod
        run: now
        env:
          ZEIT_TOKEN: ${{ secrets.ZEIT_TOKEN }}
